name: Android CI/CD

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant Permission
        run: chmod +x gradlew

      # 1️⃣ Run Lint Check
      - name: Run Lint
        run: ./gradlew lint

      # 2️⃣ Run Unit Tests
      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      # 3️⃣ Build Debug APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug

      # Upload Debug APK
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk

      # 4️⃣ Build Release AAB
      - name: Build Release AAB
        run: ./gradlew bundleRelease

      # Upload AAB
      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: release-aab
          path: app/build/outputs/bundle/release/app-release.aab

      # 5️⃣ Deploy to Google Play
#      - name: Deploy to Play Store
#        uses: r0adkll/upload-google-play@v1
#        with:
#          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT }}
#          packageName: com.yourcompany.yourapp
#          releaseFiles: app/build/outputs/bundle/release/app-release.aab
#          track: internal